data(HarvestData)
VariableList <- names(HarvestData)
data(ExperimentSummary)
data(Experiment.Site)
temporary_1 <- subset(ExperimentSummary, select = c("ExpID", "SiteID"))
temporary_2 <- subset(Experiment.Site, select = c("SiteID", "Latitude", "Longitude"))
result <- merge (temporary_1, temporary_2, by = "SiteID")
HarvestData <- merge (HarvestData, result, by = "ExpID")
save(HarvestData, file="/home/djaiswal/Research/gitprojects/sugarbag/data/HarvestData.rda")
write.csv(HarvestData, file ="/home/djaiswal/Research/gitprojects/sugarbag/inst/extdata/Harvest.With.Location.csv" )
